name: build
on: [push, pull_request]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    name: ${{ matrix.config.image }}:${{ matrix.config.tag }}
    container:
      image: ${{ matrix.config.image }}:${{ matrix.config.tag }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {image: 'quay.io/centos/centos', tag: 'centos7'}
        - {image: 'quay.io/centos/centos', tag: 'stream8'}
        - {image: 'ubuntu', tag: '18.04'}
        - {image: 'ubuntu', tag: '20.04'}
        - {image: 'ubuntu', tag: '22.04'}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (CentOS 7)
      if: ${{ matrix.config.tag == 'centos7' }}
      run: |
        yum install -y epel-release
        yum install -y R-core

    - name: Install dependencies (CentOS 8)
      if: ${{ matrix.config.tag == 'stream8' }}
      run: |
        dnf config-manager --set-enabled powertools
        dnf install -y epel-release epel-next-release
        dnf install -y R-core

    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.config.image == 'ubuntu' }}
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update && apt install -y r-base-core apt-file

    - name: Check
      env:
        LANG: C.UTF-8
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
      run: |
        Rscript -e 'install.packages("tinytest", repos="https://cran.r-project.org")'
        R CMD build . && mkdir check
        R CMD check rspm_*.tar.gz --no-manual -o check

    - name: Upload check results
      if: ${{ failure() }}
      uses: actions/upload-artifact@master
      with:
        name: r-${{ matrix.config.image }}-${{ matrix.config.tag }}-results
        path: check
